### ISSUE TITLE
Error parsing spineboy skeleton

### ISSUE THREAD

**Issue by jzcoder** [terrysimons/spine-python#1]
boneMap contains a string 'left foot' and is not a map. I'm trying to use the spineboy example from the CPP runtime.

Traceback (most recent call last):
  File "D:/dev/spine-python/src/test_rotation.py", line 23, in <module>
    skeletonData = skeletonJson.readSkeletonData(skeletonFile)
  File "D:\dev\spine-python\lib\site-packages\spine\SkeletonJson.py", line 50, in readSkeletonData
    boneData = BoneData.BoneData(name=boneMap['name'])
TypeError: string indices must be integers

**Comment by jzcoder** [comment]
My error. I was using the spineboy-walk.json instead of spineboy-skeleton.json. I see the animation example under pyguts.

**Comment by terrysimons** [comment]
Sorry, that test file shouldn't be in there.

If you download the PyPI tarball of pyguts, or check out the latest GitHub sources of spine-python you should see an examples folder in the pyguts directory.

The sources are going through a little bit of flux while I clean things up, but it should generally stay the way it is now.

I'll add a read me as well.

Let me know if you still have problems.
- Terry
